spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/dream_house_1/MyConfig.git
          username: ********
          password: ********
          default-label: master #配置文件分支
          search-paths: config  #配置文件所在根目录
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
      preferredNetworks:
        - 192.168